#!/bin/sh

fw=$1
if test ! -f ../../$fw.tar.gz; then
  echo "usage: makeimage <fhem-VERSION>"
  echo "../../<fhem-VERSION>.tar.gz must exist"
  exit 1
fi

rm -rf var
echo Extracting the fritzbox template
unzip -qo ../../priv/fritzbox7270_template.zip

rm -rf fhem/FHEM
mkdir fhem/FHEM
mkdir fhem/docs
mkdir fhem/www

cp fhemcmd.sh fhem/FHEM
cp startfhem fhem

echo Extracting $fw
rm -rf $fw
tar zxf ../../$fw.tar.gz
cd $fw
cp fhem.pl ../fhem
cp -r FHEM/* ../fhem/FHEM
cp docs/*.html ../fhem/docs
cp docs/fhem.png ../fhem/docs
cp docs/*.jpg ../fhem/docs
cp -r www/* ../fhem/www
cp examples/sample_pgm2 ../fhem/fhem.cfg

cd ..
rm -rf $fw

echo Packing again
cd fhem
perl -pi -e 's,/tmp,./log,g' fhem.cfg

cd ..
zip -qr $fw-fb7270.zip fhem
rm -rf fhem
