#!/bin/sh

fw=$1
if test ! -f ../../$fw.tar.gz; then
  echo "usage: makeimage <fhem-VERSION>"
  echo "../../<fhem-VERSION>.tar.gz must exist"
  exit 1
fi

rm -rf var
echo Extracting the fritzbox template
tar xf ../../priv/fritzbox7390_template.tar
cd var
tar zxf fhem.tar.gz
rm -rf fhem/FHEM
mkdir fhem/FHEM
mkdir fhem/docs
mkdir fhem/www
cd ..

cp install var
cp startfhem var/fhem
cp fhemcmd.sh var/fhem/FHEM


echo Extracting $fw
rm -rf $fw
tar zxf ../../$fw.tar.gz
cd $fw
cp fhem.pl ../var/fhem
cp -r FHEM/* ../var/fhem/FHEM
cp docs/*.html ../var/fhem/docs
cp docs/fhem.png ../var/fhem/docs
cp docs/*.jpg ../var/fhem/docs
cp -r www/* ../var/fhem/www
cp examples/sample_pgm2 ../var/fhem/fhem.cfg

cd ..
rm -rf $fw

echo Packing again
cd var/fhem
perl -pi -e 's,/tmp,./log,g' fhem.cfg

cd ..
tar zcf fhem.tar.gz fhem
rm -rf fhem

cd ..
tar cf $fw-fb7390.image var
rm -rf var
